import { FaqItem } from '../types/faq'

export const faqData: FaqItem[] = [
  {
    question: '🚀 How to Get Started with Resume Author - Complete Guide',
    category: 'getting-started',
    answer:
      'Welcome to Resume Author! Follow these simple steps to create your first verifiable resume:\n\n**STEP 1: Choose Your Authentication Method**\n• Google Drive Login: Click "Login or Sign Up with Google Drive" on the homepage\n• Digital Wallet: Choose "Sign Up with Learner Credential Wallet" for blockchain-based storage\n\n**STEP 2: Authentication Process**\n• For Google Drive: Sign in with your Google account and grant permissions\n• For Digital Wallet: Download the Learner Credential Wallet app from https://lcw.app first\n\n**STEP 3: Create Your Resume**\n• After login, you\'ll see "How do you want to create your resume?"\n• Choose "Start from scratch" for a blank template\n• Choose "Upload existing resume" to import resume data (PDF/text format)\n\n**STEP 4: Fill Out Your Information**\n• Complete your personal information, contact details, and summary\n• Add work experience, education, and skills\n• Include any verifiable credentials you have\n\n**STEP 5: Preview and Export**\n• Use the preview function to see how your resume looks\n• Export to PDF for traditional sharing\n• Sign your resume to create a verifiable credential\n\n**Need Help?** Visit our FAQ section or contact support for assistance!'
  },
  {
    question: '📝 How to Create a Resume from Scratch',
    category: 'using-app',
    answer:
      'Creating a resume from scratch is easy with Resume Author:\n\n**Starting the Process:**\n• Click "Start from scratch" on the import page\n• You\'ll be taken to the Resume Editor\n\n**Required Sections to Complete:**\n• Personal Information: Name, contact details, location\n• Professional Summary: Brief overview of your skills and experience\n• Work Experience: Job titles, companies, dates, descriptions\n• Education: Degrees, schools, graduation dates\n• Skills: Technical and soft skills\n\n**Optional Sections You Can Add:**\n• Certifications and Licenses\n• Professional Affiliations\n• Awards and Achievements\n• Projects and Publications\n• Languages\n• Volunteer Experience\n\n**Tips for Best Results:**\n• Use action verbs in your experience descriptions\n• Quantify achievements with numbers when possible\n• Keep descriptions concise but informative\n• Save your work frequently - drafts are automatically saved\n• Use the preview feature to check formatting\n\n**Adding Verifiable Credentials:**\n• If you have digital credentials, you can embed them directly\n• This makes your resume more trustworthy to employers\n• Credentials are cryptographically signed and verifiable'
  },
  {
    question: '📤 How to Upload and Import an Existing Resume',
    category: 'using-app',
    answer:
      'Currently, Resume Author supports manual data entry for importing existing resume information:\n\n**Upload Process:**\n• Click "Upload existing resume" on the import page\n• You can upload PDF or text files for reference\n• The system will help extract information, but manual review is required\n\n**What Gets Imported:**\n• Basic contact information\n• Work experience entries\n• Education history\n• Skills listings\n• Professional summary\n\n**Manual Review Required:**\n• Review all imported information for accuracy\n• Add missing details or correct any errors\n• Enhance descriptions with more detail if needed\n• Add any verifiable credentials you possess\n\n**Important Notes:**\n• File format support is limited in this proof-of-concept version\n• Complex formatting may not transfer perfectly\n• Always review and edit imported content\n• You can enhance the imported resume with verifiable credentials\n\n**After Import:**\n• Use the editor to refine your information\n• Add verifiable credentials for enhanced trust\n• Preview your resume before finalizing\n• Export to PDF or sign as a verifiable credential'
  },
  {
    question: '👀 How to Preview, Edit, and Export Your Resume',
    category: 'using-app',
    answer:
      'Resume Author provides multiple ways to review and share your resume:\n\n**Preview Your Resume:**\n• Click "Preview" in the editor to see the formatted version\n• The preview shows exactly how your resume will look\n• You can preview at any time during editing\n• Make sure all sections appear correctly formatted\n\n**Editing Your Resume:**\n• Use the left sidebar to navigate between sections\n• Click on any section to edit its content\n• Changes are saved automatically as you work\n• You can add or remove optional sections as needed\n\n**Export Options:**\n• **PDF Export**: Click the PDF icon to download a traditional PDF version\n• **Signed Credential**: Create a verifiable, cryptographically signed version\n• **Share Link**: Generate a secure link to share your resume online\n• **QR Code**: Get a QR code for easy mobile sharing\n\n**Managing Multiple Resumes:**\n• Access "My Resumes" to see all your created resumes\n• You can have multiple versions for different job applications\n• Edit existing resumes or create new ones\n• Organize your resumes by job type or industry\n\n**Best Practices:**\n• Always preview before exporting\n• Keep multiple versions for different job types\n• Update your resume regularly with new experiences\n• Use the verifiable credential feature for maximum trust'
  },
  {
    question: '🔐 Understanding Digital Wallets and Google Drive Storage',
    category: 'technical',
    answer:
      "Resume Author offers two secure storage options for your resume data:\n\n**Google Drive Storage:**\n• Your resumes are stored in your personal Google Drive\n• You maintain full control and ownership of your data\n• Easy to access and manage through your Google account\n• Familiar interface for most users\n• Automatic backup and sync across devices\n\n**Learner Credential Wallet (LCW):**\n• Blockchain-based storage for maximum security\n• Decentralized - you own your data completely\n• Enables verifiable credentials that employers can trust\n• Compatible with the broader credential ecosystem\n• Download from https://lcw.app\n\n**Which Should You Choose?**\n• **Google Drive**: Best for users who want familiar, easy-to-use storage\n• **Digital Wallet**: Best for users who want maximum security and verifiability\n• You can use both - they're not mutually exclusive\n\n**Security Features:**\n• All data is encrypted during storage and transmission\n• You control who has access to your resume information\n• Authentication required for all access\n• No data is shared without your explicit permission\n\n**Data Portability:**\n• Your resume data belongs to you\n• You can export and move your data at any time\n• Compatible with other credential systems\n• No vendor lock-in"
  },
  {
    question: '✅ How to Sign and Verify Your Resume Credentials',
    category: 'using-app',
    answer:
      "Resume Author creates verifiable credentials that employers can trust:\n\n**What is a Signed Resume?**\n• A cryptographically signed version of your resume\n• Proves the resume hasn't been tampered with\n• Provides verifiable proof of your claims\n• Compatible with industry standards (HR Open Standards, LER-RS)\n\n**How to Sign Your Resume:**\n• Complete all sections of your resume\n• Click \"Sign & Save\" in the preview or editor\n• Choose your signing method (Google Drive or Wallet)\n• The system creates a verifiable credential\n\n**Benefits of Signed Resumes:**\n• Employers can verify authenticity instantly\n• Reduces fraud and misrepresentation\n• Shows you're tech-savvy and forward-thinking\n• Integrates with modern HR systems\n• Builds trust with potential employers\n\n**How Employers Verify:**\n• They receive a special link or QR code\n• The verification happens automatically\n• Shows green checkmarks for verified information\n• Displays the signing authority and timestamp\n\n**What Gets Verified:**\n• Your identity as the resume author\n• That the resume hasn't been modified\n• The timestamp of when it was created\n• Any embedded verifiable credentials\n\n**Sharing Signed Resumes:**\n• Send the verification link via email\n• Include QR codes in printed versions\n• Share through professional networks\n• Embed in your online portfolio"
  },
  {
    question: '📱 How to Share Your Resume with Employers',
    category: 'using-app',
    answer:
      'Resume Author provides multiple professional ways to share your resume:\n\n**Traditional PDF Sharing:**\n• Export your resume as a PDF file\n• Attach to email applications\n• Upload to job boards and career sites\n• Print for in-person interviews\n\n**Verifiable Credential Sharing:**\n• Generate a secure sharing link\n• Create a QR code for mobile scanning\n• Send via email with verification features\n• Share through professional networks\n\n**QR Code Features:**\n• Print QR codes on business cards\n• Include in email signatures\n• Add to LinkedIn profiles\n• Use at networking events\n\n**Professional Sharing Tips:**\n• Always include a brief introduction message\n• Mention that your resume is verifiable for added credibility\n• Provide both PDF and verification link options\n• Follow up appropriately after sharing\n\n**Privacy and Security:**\n• You control who can access your resume\n• Links can be time-limited if desired\n• No personal data is exposed without permission\n• Tracking shows when your resume is viewed\n\n**For Different Scenarios:**\n• **Job Applications**: Use PDF + verification link\n• **Networking Events**: Use QR codes\n• **Online Profiles**: Embed sharing links\n• **Email Applications**: Attach PDF with verification note'
  },
  {
    question: '🔧 Troubleshooting Common Issues',
    category: 'technical',
    answer:
      "Here are solutions to common issues you might encounter:\n\n**Login Problems:**\n• Clear your browser cache and cookies\n• Try incognito/private browsing mode\n• Ensure you're using a supported browser (Chrome, Firefox, Safari)\n• Check your Google account permissions\n• For wallet issues, ensure the LCW app is properly installed\n\n**Resume Editor Issues:**\n• Refresh the page if sections aren't loading\n• Check your internet connection\n• Don't use special characters in text fields\n• Save frequently to prevent data loss\n• Try a different browser if problems persist\n\n**Preview and Export Problems:**\n• Allow pop-ups for PDF downloads\n• Check your browser's download settings\n• Ensure all required fields are completed\n• Try exporting in a different format\n• Contact support if exports consistently fail\n\n**Sharing and Verification Issues:**\n• Ensure sharing links are copied completely\n• Check that QR codes are clear and scannable\n• Verify your internet connection for online sharing\n• Test links before sending to employers\n\n**Performance Issues:**\n• Close unnecessary browser tabs\n• Use a stable internet connection\n• Clear browser cache regularly\n• Update your browser to the latest version\n\n**Getting Additional Help:**\n• Check this FAQ for more solutions\n• Contact support at support@resume-author.com\n• Report bugs through the feedback system\n• Join our community forums for peer support"
  },
  {
    question: '💡 Tips for Creating an Outstanding Resume',
    category: 'using-app',
    answer:
      "Make your resume stand out with these professional tips:\n\n**Content Best Practices:**\n• Start with a compelling professional summary\n• Use action verbs (achieved, managed, developed, led)\n• Quantify your accomplishments with numbers\n• Tailor content to each job application\n• Include relevant keywords from job descriptions\n\n**Formatting Guidelines:**\n• Keep it concise - typically 1-2 pages\n• Use consistent formatting throughout\n• Choose professional fonts and colors\n• Ensure adequate white space for readability\n• Test how it looks in both PDF and digital formats\n\n**Verifiable Credentials:**\n• Include any digital certificates you possess\n• Add professional licenses and certifications\n• Link to verified educational credentials\n• Include verified project completions\n• Showcase verified skill assessments\n\n**Section Organization:**\n• List experience in reverse chronological order\n• Group similar skills together\n• Prioritize most relevant information\n• Use bullet points for easy scanning\n• Include contact information prominently\n\n**Technology Integration:**\n• Take advantage of Resume Author's verification features\n• Include QR codes for easy mobile access\n• Use sharing links for online applications\n• Leverage the digital credential ecosystem\n\n**Final Review Checklist:**\n• Proofread for spelling and grammar errors\n• Verify all dates and details are accurate\n• Ensure contact information is current\n• Test all sharing links and QR codes\n• Get feedback from trusted colleagues"
  },
  {
    question: '❓ About Resume Author - Technical Information',
    category: 'general',
    answer:
      'Resume Author is a proof-of-concept application with specific goals and limitations:\n\n**What Resume Author Is:**\n• A demonstration of verifiable credentials in resume creation\n• Compliant with HR Open Standards and LER-RS specifications\n• Compatible with the decentralized LER ecosystem\n• A bridge between traditional and future-ready resume formats\n• Free to use during the proof-of-concept period\n\n**Technical Standards:**\n• Supports 1EdTech CLRv2 and OBv3 credentials\n• Generates HR Open Standards-compliant resumes\n• Creates verifiable credentials using blockchain technology\n• Exports traditional PDF formats for current industry needs\n\n**Current Limitations:**\n• Limited variety of credential sections\n• Import functionality is basic\n• Some advanced features are still in development\n• Designed as a proof-of-concept, not production software\n\n**Open Source Information:**\n• Available under Apache 2 License for software\n• Documentation under Creative Commons CC BY license\n• Source code available on GitHub\n• Community contributions welcome\n\n**Support and Funding:**\n• Supported by T3 Innovation Network\n• US Chamber of Commerce Foundation backing\n• Free during proof-of-concept phase\n• Feedback and suggestions encouraged\n\n**Future Development:**\n• Additional credential types planned\n• Enhanced import capabilities coming\n• More customization options in development\n• Commercial implementations possible'
  }
]
